In [1]:
import numpy as np

In [2]:
np1 = np.zeros((2, 8), int)


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np1.

In [5]:
np2 = np.ones(8, int)
np2

array([1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
np3 = np.full((2, 3), 78, int)
np3

array([[78, 78, 78],
       [78, 78, 78]])

In [11]:
np4 = np.full_like(np2, 54.8)
np4

array([54, 54, 54, 54, 54, 54, 54, 54])

In [14]:
np5 = np.arange(23, 100, 4, float)
np5

array([23., 27., 31., 35., 39., 43., 47., 51., 55., 59., 63., 67., 71.,
       75., 79., 83., 87., 91., 95., 99.])

In [15]:
py_list = [3, 24, 24, 25, 75, 982]
np6 = np.array(py_list)
np6

array([  3,  24,  24,  25,  75, 982])

In [16]:
np7 = np.array([2, 35, 65, 3])
np7

array([ 2, 35, 65,  3])

In [28]:
np6[-1]

982

In [30]:
np6[2:4]

array([24, 25])

In [46]:
np8 = np.empty((3,10), int)
np8

array([[         0,          0,          0,          0,          0,
                 0,          0,          0,          0,          0],
       [         0,          0,          0,          0,          0,
                 0,          0,          0,          0,          0],
       [         0,          0,          0,          0,          0,
                 0,          0,          0, 1528838690,      32093]])

In [49]:
np6[2:8:2]

array([24, 75])

In [50]:
np6[::2]

array([ 3, 24, 75])

In [52]:
np9 = np.array([[1, 2, 3, 4], [11, 12, 13, 14]])
np9

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [60]:
np9[0, 2:4]

array([3, 4])

In [63]:
np.sqrt(np9)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [70]:
np9.shape

(2, 4)

In [79]:
np10 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [89]:
np10.reshape(2, 4, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [90]:
np11 = np.array([1, 2, 3, 4, 5,6, 7, 8])

In [93]:
np10.shape

(4, 4)